version: "3"
services:
  raid6-0:
    restart: always
    image: raid6:latest
    container_name: raid6-0
    network_mode: "host"
    volumes:
      - raid6-0:/var/data/raid6
    environment:
      SERVER_ID: 0
  raid6-1:
    restart: always
    image: raid6:latest
    container_name: raid6-1
    network_mode: "host"
    volumes:
      - raid6-1:/var/data/raid6
    environment:
      SERVER_ID: 1
  raid6-2:
    restart: always
    image: raid6:latest
    container_name: raid6-2
    network_mode: "host"
    volumes:
      - raid6-2:/var/data/raid6
    environment:
      SERVER_ID: 2
  raid6-3:
    restart: always
    image: raid6:latest
    container_name: raid6-3
    network_mode: "host"
    volumes:
      - raid6-3:/var/data/raid6
    environment:
      SERVER_ID: 3
  raid6-4:
    restart: always
    image: raid6:latest
    container_name: raid6-4
    network_mode: "host"
    volumes:
      - raid6-4:/var/data/raid6
    environment:
      SERVER_ID: 4
  raid6-5:
    restart: always
    image: raid6:latest
    container_name: raid6-5
    network_mode: "host"
    volumes:
      - raid6-5:/var/data/raid6
    environment:
      SERVER_ID: 5
  raid6-6:
    restart: always
    image: raid6:latest
    container_name: raid6-6
    network_mode: "host"
    volumes:
      - raid6-6:/var/data/raid6
    environment:
      SERVER_ID: 6
  raid6-7:
    restart: always
    image: raid6:latest
    container_name: raid6-7
    network_mode: "host"
    volumes:
      - raid6-7:/var/data/raid6
    environment:
      SERVER_ID: 7

volumes:
  raid6-0:
  raid6-1:
  raid6-2:
  raid6-3:
  raid6-4:
  raid6-5:
  raid6-6:
  raid6-7:
